import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AddClubButton from "./components/AddClubButton"; 
import  HomeClubButton  from "./components/HomeClubButton";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-gray-50 text-black-900">
      <header className="flex items-center justify-between px-4 py-3 bg-[#CC0000] text-white">
        <HomeClubButton />
        <AddClubButton />
        </header>
        <main className=" bg-gray-50 mx-auto max-w-3x1 p-6">{children}</main>
      </body>
    </html>
  );
}
