import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-gray-50 text-black-900">
      <header className="flex items-center justify-between px-4 py-3 bg-[#CC0000] text-white">
        <h1 className="text-lg font-semibold">CSUN Club Finder</h1>
        {/* <a href="/submit" className="rounded bg-black px-3 py-1 text-sm hover:bg-gray-800">
        Club/Org: Submit or Update
        </a> */}
        </header>
        <main className=" bg-gray-50 mx-auto max-w-3x1 p-6">{children}</main>
        <footer className="bg-gray-50 px-4 py-6 text-center text-xs text-gray-500">
          © 2025 CSUN Club Finder
        </footer>
      </body>
    </html>
  );
}
